### PR TITLE
Moved glob import in setup.py to make clean command work

### PR DESCRIPTION
**Pull request by capellini**
'python setup.py clean' fails due to the glob module not being present.
Moved glob import statement to the top of the setup.py file to the top
of the file to allow the clean command to work.

### CODE REVIEW

**Comment by bashtage** [comment]
Seeing some failures here.  A bit strange.

**Comment by capellini** [comment]
Are they the same errors as the errors on the builds that failed?  Or are they different errors.  Agreed, though -- very strange.

**Comment by bashtage** [comment]
I restarted it in case there was a hiccup.

**Comment by bashtage** [comment]
Travis seems happy now.

**Comment by capellini** [comment]
Any idea what's going on with the coverage checks?  I've only made changes to setup.py.

**Comment by bashtage** [comment]
Dunno - I mostly ignore them unless they are very big.

**Pull request merged**
