### PR TITLE
Update bootstrap_examples.ipynb

### PR DESCRIPTION
**Pull request by jonathanng**

### CODE REVIEW

**Comment by bashtage** [comment]
Could you do a try except with both the old and the new?  This is changing in futures pandas (and pandas-datareader) so that the original version will work.

**Comment by jonathanng** [comment]
The original version does not work. I believe they changed the file names
on the the data website.

**Comment by bashtage** [comment]
I know, but in the master copies of pandas and pandas-datareader, this issue has been fixed (IOW Pandas will add the _TXT automatically in the future), so that pandas 0.17 will break again.  Having both versions will ensure that this notebook will continue to work once Pandas 0.17 is released.

**Comment by bashtage** [comment]
I am going to close this one.  In the future, you can amend using something like

<change arch/path/some_file.py>
```
git add arch/path/some_file.py
git commit --amend
git push -f
```

This will amend your previous commit and it is "as-if" the previous commit never happened.

**Pull request closed without merging**
