### PR TITLE
DEP: Limit statsmodels imports

### PR DESCRIPTION
**Pull request by jbrockmendel**
Get cStringIO and range imports from arch.compat.python instead of statsmodels.compat

Get cache_readonly from pandas (cython implementation, better testing)

Use dict instead of resettable_cache.  I know in sm _all_ usages of `resettable_cache` are unnecessary; am just assuming the same is true here.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Hmm the cache_readonly doesn't play nicely with the docstring_inheritor.  May need to rework it so the docstring inheritance gets applied before the cache_readonly decorator.  Or just use the sm version

**Comment by bashtage** [comment]
I think I've found this implementation to work the best. I should port it over.

https://github.com/bashtage/linearmodels/blob/master/linearmodels/utility.py#L353

**Comment by bashtage** [comment]
I am going to take an external dependency to a well thought through cached_property in the package with the same name.  Happy with the other changes.

**Comment by bashtage** [comment]
Thanks.

**Comment by jbrockmendel** [comment]
> I think I've found this implementation to work the best. I should port it over.

Do you mean port `CachedProperty` to `statsmodels`?  If so, I don't think that's necessary.  `CachedProperty` here is almost identical to statsmodels' existing `OneTimeProperty`, which if anything should be removed (5138, the thing is barely used, and one of those usages is invalid).  (I'd also like to get rid of ResettableCache there 4468, and use cache_readonly subclasses to actually do `remove_data` consistently 4421).

**Comment by bashtage** [comment]
It had a similar idea but had evolved from OTP which seems to be pretty ancient.  I'm happy to take a dependency on `cached_property` which is the evolution of what I had in linearmodels but has been tested in a much wider variety of contexts.

**Comment by bashtage** [comment]
I never remove data so I don't really need to reset (the cached_proroperty can be reset FWIW).

What annoys me about cache_readonly is that it autocompleted like a function and so you do .som<tab> and I get .some_property() which doesn't work.

**Comment by jbrockmendel** [comment]
> What annoys me about cache_readonly is that it autocompleted like a function and so you do .som and I get .some_property() which doesn't work.

Does this not happen with regular properties?  Does that happen with the pandas version as well as the sm version?

**Comment by bashtage** [comment]
Properties work as expected.  I'm not sure where pandas uses it, but I can't recall having autocomplete issues in pandas.  

I just looked at the cythonized version -- it doesn't use types so I would be surprised if it was meaningfully faster then a pure Python implementation.  An Python implementation using slots, if feasible, could actually as fast a Cython implementation (which is effectively using slots).

**Comment by bashtage** [comment]
The pandas one works normally, and I'm not surprised since it also appears to be mostly derived from the same place as the bottle.py version.

**Pull request merged**
